EChartsLearn/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^charts/', include('charts.urls'))
]

charts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2016-11-12 01:04:50
# @Author  : Alex Tang (1174779123@qq.com)
# @Link    : http://t1174779123.iteye.com
'''
	description:
'''

from django.conf.urls import url 
from . import views

app_name = 'charts'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^input/$', views.input, name = 'input'),
	url(r'^result/$', views.result, name = 'result'),
	url(r'^addData/$', views.addData, name = 'addData'),
	url(r'^addWifiData/$', views.addWifiData, name = 'addWifiData'),
	url(r'^showData/$',views.showData, name = 'showData'),
	url(r'^sendUpdateData/$',views.sendUpdateData, name = 'sendUpdateData'),

]


charts/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
import datetime

# Create your models here.

class TempLog(models.Model):
	temperature = models.FloatField()
	recv_time = models.DateTimeField('receive time')
	recv_timestamp = models.IntegerField()
	
	def was_received_recently(self):
		now = timezone.now()
		return now >= self.recv_time >= timezone.now() - datetime.timedelta(days=1)
	def __str__(self):
		return str(self.recv_time)+' '+str(self.temperature)

		

charts/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.core import serializers
import json,time

from .models import TempLog
# Create your views here.
show_date_num = 100
#首页
def index(request):
	return render(request, 'charts/index.html')
#输入数据页
def input(request):
	return render(request, 'charts/input.html')
#数据结果页
def result(request):
	latest_templog_list = TempLog.objects.order_by('-recv_time')[:show_date_num]
	context = {'latest_templog_list':latest_templog_list}
	return render(request, 'charts/result.html',context)
#处理数据
def addData(request):
	print request.POST
	temp = float(request.POST['temp'])
	print 'get temp',temp
	time_stamp = int(time.mktime(timezone.now().timetuple()))
	templog = TempLog(temperature=temp, recv_time=timezone.now(), recv_timestamp = time_stamp)
	templog.save()
	return HttpResponseRedirect(reverse('charts:result'))

#处理wifi模块数据
def addWifiData(request):
	print request.POST
	temp = float(request.POST['temp'])
	print 'get wifi temp',temp
	time_stamp = int(time.mktime(timezone.now().timetuple()))
	templog = TempLog(temperature=temp, recv_time=timezone.now(), recv_timestamp = time_stamp)
	templog.save()
	return HttpResponse('<h1>get wifi temp </h1>')

#显示温度数据页面
def showData(request):
	#TODO: 能否只返回两个字段
	temp_list = TempLog.objects.order_by('recv_time')
	temp_datas = getJsonData(temp_list)
	# temp_datas = serializers.serialize('json',temp_list)
	print 'length: ',len(temp_datas)
	context = {'temp_datas':json.dumps(temp_datas)}
	return render(request, 'charts/showdata.html', context)
#由QuerySet得到Json数据的子函数
def getJsonData(temp_list):
	temp_datas = []
	for templog in temp_list:
		# temp_data = {'time':time_stamp,
		# 			 'temperature':templog.temperature}
		temp_data = [templog.recv_timestamp*1000, templog.temperature]
		temp_datas.append(temp_data)
	return temp_datas

#向前端返回更新数据的方法
def sendUpdateData(request):
	if request.method == 'POST':
		print request.POST
		latest_time = int(request.POST['latest_time'])/1000
		print 'POST from JS , latest_time = ',latest_time
		#查询数据库得到更新的数据
		new_list = TempLog.objects.filter(recv_timestamp__gt=latest_time)
		print "new_list:",len(new_list)
		new_data = getJsonData(new_list)
		#返回数据给前端
		return HttpResponse(json.dumps(new_data))

charts/templates/charts/index.html
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>温度监控</title>
		{% load static %}
		<script src="{% static 'charts/jquery/jquery-3.1.1.js' %}"></script>
		<script src="{% static 'charts/highstock/highstock.js' %}"></script>
		<script src="{% static 'charts/highstock/modules/exporting.js' %}"></script>
		<script type="text/javascript">
            $(function () {
			    Highcharts.setOptions({
			        global : {
			            useUTC : false
			        }
			    });
			    // Create the chart
			    $('#container').highcharts('StockChart', {
			        chart : {
			            events : {
			                load : function () {
			                    // set up the updating of the chart each second
			                    var series = this.series[0];
			                    setInterval(function () {
			                        var x = (new Date()).getTime(), // current time
			                            y = Math.round(Math.random() * 100);
			                        series.addPoint([x, y], true, true);
			                    }, 1000);
			                }
			            }
			        },
			        rangeSelector: {
			            buttons: [{
			                count: 1,
			                type: 'minute',
			                text: '1M'
			            }, {
			                count: 5,
			                type: 'minute',
			                text: '5M'
			            }, {
			                type: 'all',
			                text: 'All'
			            }],
			            inputEnabled: false,
			            selected: 0
			        },
			        title : {
			            text : 'Live random data'
			        },
			        exporting: {
			            enabled: false
			        },
			        series : [{
			            name : 'Random data',
			            data : (function () {
			                // generate an array of random data
			                var data = [], time = (new Date()).getTime(), i;
			                for (i = -999; i <= 0; i += 1) {
			                    data.push([
			                        time + i * 1000,
			                        Math.round(Math.random() * 100)
			                    ]);
			                }
			                alert(data[0])
			                return data;
			            }())
			        }]
			    });
			});
		</script>
	</head>
	<body>
		<div id="container" style="height: 400px; min-width: 310px"></div>
	</body>
</html>

charts/templates/charts/input.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>输入温度数据</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
</head>
<body>
    <h1>输入温度数据</h1>
    {% if error_message %}
    	<p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'charts:addData' %}", method="post">
    <!-- {% csrf_token %} -->
    <label>输入温度</label>
    <input type="text" name="temp"><br />
    <input type="submit" value="提交">
    </form>
</body>
</html>

charts/templates/charts/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>温度数据</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
</head>
<body>
    {% if latest_templog_list %}
    	<ul>
    	{% for templog in latest_templog_list %}
    		<p>序号：{{ forloop.counter }} \t时间：{{ templog.recv_time }} 温度：{{ templog.temperature }}</p>
    	{% endfor %}
    	</ul>
    {% else %}
    	<p>没有温度数据</p>
    {% endif %}
    <a href="{% url 'charts:input' %}">继续输入</a>
</body>
</html>

charts/templates/charts/showdata.html
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>温度监控</title>
		{% load static %}
		<script src="{% static 'charts/jquery/jquery-3.1.1.js' %}"></script>
		<script src="{% static 'charts/highstock/highstock.js' %}"></script>
		<script src="{% static 'charts/highstock/modules/exporting.js' %}"></script>
		<script type="text/javascript">
			'use strict';
			//得到初始数据
			var temp_datas = {{ temp_datas|safe }};
			alert(temp_datas[0]);
			var latest_time = temp_datas[temp_datas.length-1][0]
			alert('latest_time:'+latest_time)
			//查询得到更新数据
			function getNewTemp(series){
				var if_receive = false;
				var new_data = [];
				var post_data = {
					'latest_time':latest_time,
				};
				$.ajax({
					url: "{% url 'charts:sendUpdateData' %}",
					type: 'POST',
					data: post_data,
					// dataType: "json",
					success: function (data){
						new_data = JSON.parse(data);
						$('#message1').html(data);
						$('#message2').html(new_data[0][1]+1);
						if_receive = true;
						
						var i;
						for (i = 0;i<new_data.length;i++){
							series.addPoint(new_data[i],true,true);
							$('#message3').html(new_data[i])
						}
						this.latest_time = new_data[new_data.length-1][0];

					},
					// alawys: function(){
					// 	return new_data;
					// }
				});
				// while(!if_receive){
				// 	;
				// }
			}
            $(function () {
			    Highcharts.setOptions({
			        global : {
			            useUTC : false
			        }
			    });
			    // Create the chart
			    $('#container').highcharts('StockChart', {
			        chart : {
			            events : {
			                load : function () {
			                    // set up the updating of the chart each second
			                    var series = this.series[0];
			                    setInterval(function () {
			                        var if_receive = false;
									var new_data = [];
									var post_data = {
										'latest_time':latest_time,
									};
									$.ajax({
										url: "{% url 'charts:sendUpdateData' %}",
										type: 'POST',
										data: post_data,
										// dataType: "json",
										success: function (data){
											new_data = JSON.parse(data);
											$('#message1').html(latest_time);
											$('#message2').html(new_data[0][1]);
											if_receive = true;
											
											var i;
											for (i = 0;i<new_data.length;i++){
												series.addPoint(new_data[i],true,true);
												$('#message3').html(new_data[i])
											}
											latest_time = new_data[new_data.length-1][0];

										},
									});
			                    }, 1000);
			                }
			            }
			        },
			        rangeSelector: {
			            buttons: [{
			                count: 1,
			                type: 'minute',
			                text: '1M'
			            }, {
			                count: 5,
			                type: 'minute',
			                text: '5M'
			            }, {
			                type: 'all',
			                text: 'All'
			            }],
			            inputEnabled: false,
			            selected: 0
			        },
			        title : {
			            text : 'Live random data'
			        },
			        exporting: {
			            enabled: false
			        },
			        series : [{
			            name : 'Random data',
			            data : temp_datas
			        }]
			    });
			});
		</script>
	</head>
	<body>
		<p id="message1">No message1</p>
		<p id="message2">No message2</p>
		<div id="container" style="height: 400px; min-width: 310px"></div>
		<p id="message3">No message3</p>
	</body>
</html>